name: clima
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  geolocator: ^7.4.1
  http: ^0.13.3
  flutter_spinkit: ^5.1.0
  flutter_icons: ^1.1.0
  date_format: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
  - images/09d@2x.png

  fonts:
  - family: Quicksand
    fonts:
    - asset: fonts/Quicksand-VariableFont_wght.ttf
      weight: 900